### ISSUE TITLE
Install Vim plugins example

### ISSUE THREAD

**Issue by 4zo4** [devjoe/vim-codequery#19] opened 2017-06-29 19:44 UTC
Hi there,

I installed codequery and it works fine as a standalone. The displayed 'vim-codequery' demo looks very powerful. I followed the instructions on how to install the Vim plugins. Per the installation example I used the 'Plug' plugin manager:

1.   ~/.vim/autoload$ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
2. ~/.vim$ mkdir plugged
3. ~/.vim/plugged$ git clone https://github.com/devjoe/vim-codequery.git
4. vim .vimrc and added (I missed adding the 'unity' plugin for the initial test)  
call plug#begin('~/.vim/plugged')
Plug 'vim-codequery'
call plug#end()
5. invoke gvim (version 8.0.685) raised the following error:

"[vim-plug] Invalid argument: vim-codequery (implicit `vim-scripts' expansion is deprecated)"

Can both 'vim-codequery' and 'unity' plugins be installed without a plugin manager? It would be great if instructions were available somewhere.

If a plugin manager is required, can the installation example show a working case?

Thank you,

4zo4

**Comment by devjoe** [comment] 2017-07-02 04:32
Hi @4zo4 ,
  
Just change `vim-codequery` to `devjoe/vim-codequery` in step 4. In fact, you don't have to download vim-codequery manually. Just let `plug` manager help you to download any plugin from Github. Or you can specify a complete path to the vim-codequery directory, such as `~/.vim/plugged/vim-codequery`.  

FYI, you can find the cause of this exception [here](https://github.com/junegunn/vim-plug/blob/master/plug.vim).
  
Vim8 comes with a primitive plugin manager. Let me take some time to try.
I will rewrite installation part because of this issue and #18.  
  
Thank you!

**Comment by devjoe** [comment] 2017-07-02 07:12
Oh, it's quite easy to use Vim8's package manager.
Installation guide was done in #18. So I closed this issue.  
  
Still feel free to ask me any question.

**Closed as completed by devjoe** 2017-07-02 07:12 UTC
